_target_: models.deterministic_hand_dit.HandDeterministicDiT
d_model: 512
backbone: ${backbone}
hand_encoder: ${hand_encoder}
dit: ${dit}
loss_cfg: ${loss}
optimizer_cfg: ${optimizer}
use_norm_data: true