name: ptv3
variant: light  # light | base | no_flash
use_flash_attention: true  # true | false
grid_size: 0.02

encoder_channels: [32, 64, 128, 256, 512]
encoder_depths: [1, 1, 2, 2, 1]
encoder_num_head: [2, 4, 8, 16, 16]
enc_patch_size: [1024, 1024, 1024, 1024, 1024]

decoder_channels: [512, 256, 128, 64]
decoder_depths: [1, 2, 1, 1]
dec_patch_size: [1024, 1024, 1024, 1024]

mlp_ratio: 2
out_dim: 512
input_feature_dim: 1
dec_num_head: [4, 4, 8, 16]
use_xyz: true  # true | false
normalize_xyz: true  # true | false
